# Generated by Django 3.1.7 on 2021-03-28 20:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ffutche', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholarship_id', models.CharField(max_length=120)),
                ('denomination', models.CharField(max_length=120)),
                ('reffered_studies', models.CharField(max_length=120)),
                ('minimum_amount', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=120)),
                ('criteria', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('school_type', models.CharField(max_length=120)),
                ('address1', models.CharField(max_length=120)),
                ('address2', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('country', models.CharField(max_length=120)),
                ('contact_name', models.CharField(max_length=120)),
                ('contact_phone1', models.CharField(max_length=120)),
                ('contact_phone2', models.CharField(max_length=120)),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='type',
            new_name='user_type',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Student_Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_attended', models.CharField(max_length=120)),
                ('class_type', models.CharField(max_length=120)),
                ('grade', models.CharField(max_length=120)),
                ('degree', models.CharField(max_length=120)),
                ('rank', models.CharField(max_length=120)),
                ('dismissal_reason', models.CharField(max_length=120)),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ffutche.school')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ffutche.user')),
            ],
        ),
    ]
