# Generated by Django 3.1.7 on 2021-04-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffutche', '0006_auto_20210412_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='denomination',
            field=models.CharField(max_length=130),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='description',
            field=models.CharField(max_length=130),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='minimum_amount',
            field=models.CharField(max_length=130),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='preffered_studies',
            field=models.CharField(max_length=130),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='scholarship_id',
            field=models.CharField(max_length=130),
        ),
    ]
